# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-02-12 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField()),
                ('start_date', models.DateField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
