# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-02-12 02:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MOOL_APP', '0002_auto_20200211_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='start_date',
            field=models.DateField(default=datetime.date(2020, 2, 11)),
        ),
    ]
