# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-02-12 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MOOL_APP', '0003_auto_20200211_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='start_date',
            field=models.DateField(),
        ),
    ]
