# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-02-12 04:52
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('MOOL_APP', '0004_auto_20200211_1839'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='restaurant',
            managers=[
                ('validation', django.db.models.manager.Manager()),
            ],
        ),
    ]
