# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-02-12 04:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MOOL_APP', '0005_auto_20200211_2052'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='restaurant',
            managers=[
            ],
        ),
    ]
