# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-02-18 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MOOL_APP', '0006_auto_20200211_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('restaurants', models.ManyToManyField(related_name='restaurants', to='MOOL_APP.Restaurant')),
            ],
        ),
    ]
