# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-02-18 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MOOL_APP', '0007_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='restaurants',
            field=models.ManyToManyField(related_name='products', to='MOOL_APP.Restaurant'),
        ),
    ]
