# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-02-18 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MOOL_APP', '0008_auto_20200218_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='start_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='restaurant_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='phone_number',
            new_name='number',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='code',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
