# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-02-18 23:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MOOL_APP', '0010_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='restaurants',
        ),
        migrations.AddField(
            model_name='setup',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MOOL_APP.Product'),
        ),
        migrations.AddField(
            model_name='setup',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MOOL_APP.Restaurant'),
        ),
    ]
