# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-02-19 00:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MOOL_APP', '0011_auto_20200218_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setup',
            name='price',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='setup',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setup', to='MOOL_APP.Product'),
        ),
        migrations.AlterField(
            model_name='setup',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setup', to='MOOL_APP.Restaurant'),
        ),
    ]
